spring:
  datasource:
    username: admin
    password: 1234qwer!
    url: jdbc:mysql://yu-market.c4e8qukc2vf7.ap-northeast-2.rds.amazonaws.com/yumarket?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

server:
  port: 9000